### ISSUE TITLE
Warnings when compiled for ARM

### ISSUE THREAD

**Issue by ThE-MaRaC** [MEONMedical/Log4Qt#10]
The following warnings are visible while compiling with android_armv7:
In file included from C:\Qt\5.6\android_armv7\include/QtCore/qhash.h:40:0,
                 from C:\Qt\5.6\android_armv7\include/QtCore/qshareddata.h:40,
                 from C:\Qt\5.6\android_armv7\include\QtCore/qsharedpointer.h:39,
                 from C:\Qt\5.6\android_armv7\include\QtCore/QSharedPointer:1,
                 from ..\..\..\Log4Qt\src\log4qt\log4qtsharedptr.h:4,
                 from ..\..\..\Log4Qt\src\log4qt\layout.h:29,
                 from ..\..\..\Log4Qt\src\log4qt\appender.h:28,
                 from ..\..\..\Log4Qt\src\log4qt\appenderskeleton.h:28,
                 from ..\..\..\Log4Qt\src\log4qt\appenderskeleton.cpp:25:
C:\Qt\5.6\android_armv7\include/QtCore/qlist.h: In instantiation of 'void QList<T>::node_copy(QList<T>::Node*, QList<T>::Node*, QList<T>::Node*) [with T = QVariant]':
C:\Qt\5.6\android_armv7\include/QtCore/qlist.h:805:58:   required from 'QList<T>::QList(const QList<T>&) [with T = QVariant]'
..\..\..\Log4Qt\src\log4qt\helpers/logerror.h:498:12:   required from here
C:\Qt\5.6\android_armv7\include/QtCore/qlist.h:465:17: warning: cast from 'QList<QVariant>::Node*' to 'QVariant*' increases required alignment of target type [-Wcast-align]
                 new (current) T(*reinterpret_cast<T*>(src));

Check the following thread for more info: https://groups.google.com/forum/#!topic/qt-project-list-development/CGZlE5o5Bic

I am using the following patch as a workaround (g++.pri):
  win32 {
    NORMAL_CXXFLAGS += -Wcast-align
  }

Full build log:
[build.txt](https://github.com/MEONMedical/Log4Qt/files/618279/build.txt)

Regards,
ThE-MaRaC

**Comment by andibacher** [comment]
Out of scope.
