### ISSUE TITLE
Set %F %M %L in properties file, but it can't work in windows

### ISSUE THREAD

**Issue by wanguangtong** [MEONMedical/Log4Qt#34]
I use Log4Qt-master code,and build in Qt 5.7.0.I set proterty through protpery file.I set " log4j.appender.daily.layout=org.apache.log4j.PatternLayout" and "log4j.appender.daily.layout.ConversionPattern=[%d{yyyy-MM-dd HH:mm:ss}] [%F:%M:%L] %-5p [%c] - %m%n".But Output result is "[2018-11-14 12:20:08] [::-1] INFO  [daily] - Test1",file name,method,line num are wrong.

**Comment by andibacher** [comment]
Do you use the macros l4qError(..), l4qError(..) for logging? file, line, and function are only set if you use this macros. 
If you log with:
`logger()->debug() << "Debug output";`
or 
`logger()->warn("Warning");`
file, line, and function are nit set.

**Comment by andibacher** [comment]
I can not reproduce the problem and got no feedback how this is used. When using the appropriate macro l4qError(..), l4qError(..),... this works on all supported platform.
