### ISSUE TITLE
log4qt/log4qtshared file not found

### ISSUE THREAD

**Issue by aksuna** [MEONMedical/Log4Qt#35]
I had build and install log4qt as a shared library either in Ubuntu 18.04 and in IOs 10.14
in both enviroments I get successfull to link the dynamic library . The only one issue is that when I build my project I get an error 'log4qt/log4qtshared.h' in logerror.h file not found

**Comment by andibacher** [comment]
Actually I can not reproduce this if the include path to log4qt in your project is set correct this should work. If not provide a small example. For now I will close this issue.
