### ISSUE TITLE
dailyfileappender.cpp,need add #include <QStringBuilder>

### ISSUE THREAD

**Issue by libaineu2004** [MEONMedical/Log4Qt#40]
dailyfileappender.cpp,need add #include < QStringBuilder >

`QString DailyFileAppender::appendDateToFilename() const
{
    QFileInfo fi(mOriginalFilename);
    return fi.absolutePath() % QStringLiteral("/") % fi.baseName() % mLastDate.toString(mDatePattern) % QStringLiteral(".") % fi.completeSuffix();
}`

Because "%" is an overloaded operator, if the source file does not include this header file #include < QStringBuilder >, it will conflict with "%" overloaded operators of other third-party libraries.

**Comment by andibacher** [comment]
Fixed in the master and next version.
