### ISSUE TITLE
Log4Qt-1.5.1\src\log4qt\ttcclayout.h:118, enum DateFormat has errors

### ISSUE THREAD

**Issue by libaineu2004** [MEONMedical/Log4Qt#41]
Log4Qt-1.5.1\src\log4qt\ttcclayout.h:118, enum DateFormat has errors

The source code is written this:
`
enum DateFormat
    {
        /*! The none date format string is "NONE".  */
        NONE,
        /*!
         * The iso8601 date format string is "ISO8601". The date will be
         * formatted as yyyy-MM-dd hh:mm:ss.zzz.
         */
        ISO8601,
        /*!
         * The absolute date format string is "ABSOLUTE". The date will be
         * formatted as HH:mm:ss.zzz.
         */
        ABSOLUTE,
        /*!
         * The date date format string is "DATE". The date will be formatted
         * as MMM YYYY HH:mm:ss.zzz.
         */
        DATE,
        /*!
         * The relative date format string is "RELATIVE". The date will be
         * formatted as milliseconds since start of the program.
         */
        RELATIVE
    };
`
My programming environment is Windows, here the DateFormat enumeration values ABSOLUTE and RELATIVE will conflict with the Windows header files, for example
C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.17763.0 \ um \ wingdi.h: 1903
/ * Coordinate Modes * /
#define ABSOLUTE 1
#define RELATIVE 2

I recommend changing the name of the DateFormat enum variable to something else.

**Comment by andibacher** [comment]
Should be possible to change the Enums. I will look into it.

**Comment by andibacher** [comment]
Done.
