### ISSUE TITLE
Wrong installation directories

### ISSUE THREAD

**Issue by sjacek** [MEONMedical/Log4Qt#51]
I use /usr/bin/qmake from Linux Mint distribution.
Commands `qmake; make; make install` do install to catalogs /lib and /include.
It should be installed to /usr/lib and /usr/include.

Log from installation:

`
jacek@kaczorek:~/Projekty/Qt/Log4Qt$ sudo make install
cd src/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/jacek/Projekty/Qt/Log4Qt/src/src.pro ) && make -f Makefile install
make[1]: Entering directory '/home/jacek/Projekty/Qt/Log4Qt/src'
cd log4qt/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/log4qt.pro ) && make -f Makefile install
make[2]: Entering directory '/home/jacek/Projekty/Qt/Log4Qt/src/log4qt'
/usr/lib/qt5/bin/qmake -install qinstall -exe ../../bin/liblog4qt.so.1.0.0 /lib/liblog4qt.so.1.0.0
strip --strip-unneeded /lib/liblog4qt.so.1.0.0
ln -f -s liblog4qt.so.1.0.0 /lib/liblog4qt.so
ln -f -s liblog4qt.so.1.0.0 /lib/liblog4qt.so.1
ln -f -s liblog4qt.so.1.0.0 /lib/liblog4qt.so.1.0
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/appender.h /include/log4qt/appender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/appenderskeleton.h /include/log4qt/appenderskeleton.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/asyncappender.h /include/log4qt/asyncappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/basicconfigurator.h /include/log4qt/basicconfigurator.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/binaryfileappender.h /include/log4qt/binaryfileappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/binarylayout.h /include/log4qt/binarylayout.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/binarylogger.h /include/log4qt/binarylogger.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/binaryloggingevent.h /include/log4qt/binaryloggingevent.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/binarylogstream.h /include/log4qt/binarylogstream.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/binarytotextlayout.h /include/log4qt/binarytotextlayout.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/binarywriterappender.h /include/log4qt/binarywriterappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/consoleappender.h /include/log4qt/consoleappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/dailyfileappender.h /include/log4qt/dailyfileappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/dailyrollingfileappender.h /include/log4qt/dailyrollingfileappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/fileappender.h /include/log4qt/fileappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/hierarchy.h /include/log4qt/hierarchy.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/layout.h /include/log4qt/layout.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/level.h /include/log4qt/level.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/log4qt.h /include/log4qt/log4qt.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/log4qtshared.h /include/log4qt/log4qtshared.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/log4qtsharedptr.h /include/log4qt/log4qtsharedptr.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/logger.h /include/log4qt/logger.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/loggerrepository.h /include/log4qt/loggerrepository.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/loggingevent.h /include/log4qt/loggingevent.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/logmanager.h /include/log4qt/logmanager.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/logstream.h /include/log4qt/logstream.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/mainthreadappender.h /include/log4qt/mainthreadappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/mdc.h /include/log4qt/mdc.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/ndc.h /include/log4qt/ndc.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/patternlayout.h /include/log4qt/patternlayout.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/propertyconfigurator.h /include/log4qt/propertyconfigurator.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/qmllogger.h /include/log4qt/qmllogger.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/rollingbinaryfileappender.h /include/log4qt/rollingbinaryfileappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/rollingfileappender.h /include/log4qt/rollingfileappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/signalappender.h /include/log4qt/signalappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/simplelayout.h /include/log4qt/simplelayout.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/simpletimelayout.h /include/log4qt/simpletimelayout.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/systemlogappender.h /include/log4qt/systemlogappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/ttcclayout.h /include/log4qt/ttcclayout.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/writerappender.h /include/log4qt/writerappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/xmllayout.h /include/log4qt/xmllayout.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/telnetappender.h /include/log4qt/telnetappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/helpers/appenderattachable.h /include/log4qt/helpers/appenderattachable.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/helpers/binaryclasslogger.h /include/log4qt/helpers/binaryclasslogger.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/helpers/classlogger.h /include/log4qt/helpers/classlogger.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/helpers/configuratorhelper.h /include/log4qt/helpers/configuratorhelper.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/helpers/datetime.h /include/log4qt/helpers/datetime.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/helpers/dispatcher.h /include/log4qt/helpers/dispatcher.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/helpers/factory.h /include/log4qt/helpers/factory.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/helpers/initialisationhelper.h /include/log4qt/helpers/initialisationhelper.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/helpers/logerror.h /include/log4qt/helpers/logerror.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/helpers/optionconverter.h /include/log4qt/helpers/optionconverter.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/helpers/patternformatter.h /include/log4qt/helpers/patternformatter.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/helpers/properties.h /include/log4qt/helpers/properties.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/spi/filter.h /include/log4qt/spi/filter.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/varia/binaryeventfilter.h /include/log4qt/varia/binaryeventfilter.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/varia/debugappender.h /include/log4qt/varia/debugappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/varia/denyallfilter.h /include/log4qt/varia/denyallfilter.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/varia/levelmatchfilter.h /include/log4qt/varia/levelmatchfilter.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/varia/levelrangefilter.h /include/log4qt/varia/levelrangefilter.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/varia/listappender.h /include/log4qt/varia/listappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/varia/nullappender.h /include/log4qt/varia/nullappender.h
/usr/lib/qt5/bin/qmake -install qinstall /home/jacek/Projekty/Qt/Log4Qt/src/log4qt/varia/stringmatchfilter.h /include/log4qt/varia/stringmatchfilter.h
make[2]: Leaving directory '/home/jacek/Projekty/Qt/Log4Qt/src/log4qt'
make[1]: Leaving directory '/home/jacek/Projekty/Qt/Log4Qt/src'
cd tests/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/jacek/Projekty/Qt/Log4Qt/tests/tests.pro ) && make -f Makefile install
make[1]: Entering directory '/home/jacek/Projekty/Qt/Log4Qt/tests'
cd log4qttest/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/jacek/Projekty/Qt/Log4Qt/tests/log4qttest/log4qttest.pro ) && make -f Makefile install
make[2]: Entering directory '/home/jacek/Projekty/Qt/Log4Qt/tests/log4qttest'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/jacek/Projekty/Qt/Log4Qt/tests/log4qttest'
cd binaryloggertest/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/jacek/Projekty/Qt/Log4Qt/tests/binaryloggertest/binaryloggertest.pro ) && make -f Makefile install
make[2]: Entering directory '/home/jacek/Projekty/Qt/Log4Qt/tests/binaryloggertest'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/jacek/Projekty/Qt/Log4Qt/tests/binaryloggertest'
cd dailyfileappendertest/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/jacek/Projekty/Qt/Log4Qt/tests/dailyfileappendertest/dailyfileappendertest.pro ) && make -f Makefile install
make[2]: Entering directory '/home/jacek/Projekty/Qt/Log4Qt/tests/dailyfileappendertest'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/jacek/Projekty/Qt/Log4Qt/tests/dailyfileappendertest'
cd filewatcher/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/jacek/Projekty/Qt/Log4Qt/tests/filewatcher/filewatcher.pro ) && make -f Makefile install
make[2]: Entering directory '/home/jacek/Projekty/Qt/Log4Qt/tests/filewatcher'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/jacek/Projekty/Qt/Log4Qt/tests/filewatcher'
make[1]: Leaving directory '/home/jacek/Projekty/Qt/Log4Qt/tests'
cd examples/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/jacek/Projekty/Qt/Log4Qt/examples/examples.pro ) && make -f Makefile install
make[1]: Entering directory '/home/jacek/Projekty/Qt/Log4Qt/examples'
cd basic/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/jacek/Projekty/Qt/Log4Qt/examples/basic/basic.pro ) && make -f Makefile install
make[2]: Entering directory '/home/jacek/Projekty/Qt/Log4Qt/examples/basic'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/jacek/Projekty/Qt/Log4Qt/examples/basic'
cd propertyconfigurator/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/jacek/Projekty/Qt/Log4Qt/examples/propertyconfigurator/propertyconfigurator.pro ) && make -f Makefile install
make[2]: Entering directory '/home/jacek/Projekty/Qt/Log4Qt/examples/propertyconfigurator'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/jacek/Projekty/Qt/Log4Qt/examples/propertyconfigurator'
make[1]: Leaving directory '/home/jacek/Projekty/Qt/Log4Qt/examples'
`

**Comment by sjacek** [comment]
It seems that $$INSTALL_PREFIX is undefined

**Comment by andibacher** [comment]
Does 
`qmake INSTALL_PREFIX=/usr/local`
not work?

**Comment by sjacek** [comment]
I didn't tested `qmake INSTALL_PREFIX=..`
According to the README qmake itself should be enough
