### ISSUE TITLE
include in your project , The instructions seem incomplete

### ISSUE THREAD

**Issue by niudali1** [MEONMedical/Log4Qt#55]
include in your project
Can also be used by adding the log4qt source directly to your Qt project file by adding the following line: include(/src/log4qt/log4qt.pri)
This doesn't seem to work, you still need to add build.pri and g++.pri,Is that right?

**Comment by andibacher** [comment]
You are right you need build.pri for the log4qt version. g++.pri is not realy needed you can the stuff you need to your own pro file.
