### ISSUE TITLE
Unable to write file

### ISSUE THREAD

**Issue by JXT-Eden** [MEONMedical/Log4Qt#56]
os: win10
qt:5.10.0
std:c++11
compiler:vs2015

Encapsulated as a singleton mode, in a multi-threaded environment, the use of DailyFileAppender mode, sometimes cannot write to the file and no error msg.

**Comment by andibacher** [comment]
Have or can you enabled the Logging of Log4Qt itself? For example in a log4qt property File with log4j.Debug=ALL or directly on the LogManger Logger LogManager::logLogger()->setLevel(....).

**Comment by JXT-Eden** [comment]
> Have or can you enabled the Logging of Log4Qt itself? For example in a log4qt property File with log4j.Debug=ALL or directly on the LogManger Logger LogManager::logLogger()->setLevel(....).

![conf](https://user-images.githubusercontent.com/9624017/112249729-390a7580-8c93-11eb-8b15-185a45eedbe8.png)
Info is used in the code,if a log is large, whether it will block?

**Comment by JXT-Eden** [comment]
close
