### ISSUE TITLE
AppVeyor no longer provides support for the Qt5.14 build environment

### ISSUE THREAD

**Issue by kuzzh** [MEONMedical/Log4Qt#73]
After some investigation, I found that appveyor removed support for Qt 5.14.2 in an update on April 2, 2022, so there is no longer a compiled environment for Qt 5.14. You may need to synchronize and update the appveyor.yml file.

### Reference.
1. [src/_updates/2022-04-02.md](https://github.com/appveyor/website/commit/01604773a0070969c273923c60f90e08b541bd2c) 
2. [src/docs/windows-images-software.md](https://github.com/appveyor/website/pull/820/commits/d46c2eb83543b9860ad681f52d78da2cf9da5434#diff-3e6e1c05b80ab74b59e11dd5581c3cf83dfd43bdab4eef55dc906d97379e8664)

_Originally posted by @kuzzh in https://github.com/MEONMedical/Log4Qt/issues/72#issuecomment-1172998139_

**Comment by andibacher** [comment]
Fixed on master.
