### ISSUE TITLE
removeAppender must cause deadlock

### ISSUE THREAD

**Issue by lyqdy** [MEONMedical/Log4Qt#77]
void AppenderAttachable::removeAppender(const QString &name)
{
    QWriteLocker locker(&mAppenderGuard); // it must be removed!
    AppenderSharedPtr pAppender = appender(name);
    if (pAppender)
        removeAppender(pAppender);
}

**Comment by andibacher** [comment]
As the mutex allows recursive lock it should not lock. But removed unnecessary lock.
