### ISSUE TITLE
Log4Qt`s DailyFileAppender log speed slower than spdlog`s basic_logger_st

### ISSUE THREAD

**Issue by xiaocai123123** [MEONMedical/Log4Qt#81]
Hello!
I use Log4Qt(DailyFileAppender) and spdlog(basic_logger_st) to test the speed of log to file
500000 items(no flush) like below "Hello world"
DailyFileAppender costed 15777ms
basic_logger_st costed 2731ms
So how can i improve the log speed when i use Log4Qt?

**Comment by andibacher** [comment]
Log4Qt aim was not to build a "Very fast" logger like spdlog. Log4Qt aim was to have a log4j like logging framework for Qt.
